image: "python:3.7"

before_script:
  - python --version
  - pip --version
  - pip install pylint

stages:
  - pylint

pylint_api:
  stage: pylint
  script:
  - pip install -r api2/requirements.txt
  - find ./api2/ -type f -name "*.py" | xargs pylint --disable=W0703 --max-line-length=133

pylint_car_recognition:
  stage: pylint
  script:
  - pip install -r api2/requirements.txt
  - find ./car_recognizer/ -type f -name "*.py" | xargs pylint --disable=W0703,C0103,E0401,R0914,R0903 --max-line-length=133

pylint_streaming_scraper:
  stage: pylint
  script:
  - pip install -r streaming_scraper/requirements.txt
  - find ./streaming_scraper/ -type f -name "*.py" | xargs pylint --disable=W0703,E0401 --max-line-length=133
